# Generated by Django 2.2 on 2020-07-11 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_app', '0002_remove_users_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='information',
        ),
    ]
