# Generated by Django 2.2 on 2020-07-13 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_app', '0003_remove_products_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('card_number', models.IntegerField()),
                ('expiration', models.DateTimeField()),
                ('card_code', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards_of_user', to='grocery_app.Users')),
            ],
        ),
    ]
