# Generated by Django 2.2 on 2020-07-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_app', '0004_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='zipcode',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
    ]
