# Generated by Django 2.2 on 2020-07-14 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_app', '0005_users_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='liked_product',
            field=models.BooleanField(default=False),
        ),
    ]
