# Generated by Django 2.2 on 2020-07-14 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_app', '0006_products_liked_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='liked_product',
            field=models.BooleanField(default=True),
        ),
    ]
