# Generated by Django 2.2 on 2020-07-15 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_app', '0007_auto_20200714_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='liked_product',
        ),
    ]
