# Generated by Django 2.2 on 2020-07-15 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_app', '0008_remove_products_liked_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='products',
            name='quantity',
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_of_user', to='grocery_app.Users')),
                ('product', models.ManyToManyField(related_name='orders', to='grocery_app.Products')),
            ],
        ),
    ]
