# Generated by Django 2.2 on 2020-07-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_app', '0009_auto_20200715_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(default='C:/Users/Owner/Desktop/python_stack/noorani_project_modified/noorani_project', upload_to='C:/Users/Owner/Desktop/python_stack/noorani_project_modified/noorani_project'),
        ),
    ]
