# Generated by Django 2.2 on 2020-07-16 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_app', '0013_auto_20200716_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='product',
        ),
        migrations.AddField(
            model_name='orders',
            name='product',
            field=models.ManyToManyField(related_name='orders', to='grocery_app.Products'),
        ),
    ]
