# Generated by Django 2.2 on 2020-07-20 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_app', '0014_auto_20200716_1447'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Card',
        ),
    ]
